apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: cluster-operator-2.1.9
  namespace: giantswarm
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-operator
  namespace: giantswarm
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 2.1.9
status:
  appVersion: ""
  release:
    lastDeployed: null
    status: ""
  version: ""
